/**
 * PeakUp Sports Terms of Service content (structured from peakup-terms.pdf).
 * @module containers/TermsOfServicePage/termsContent
 */

export const TERMS_PDF_URL = '/PeakUp_Terms_of_Service_Professional.pdf';
export const TERMS_LAST_UPDATED = '8 April 2026';

export const TERMS_NAV = [
  {
    id: 'definitions',
    label: 'Definitions',
  },
  {
    id: 'platform',
    label: 'Platform',
  },
  {
    id: 'accounts',
    label: 'Accounts',
  },
  {
    id: 'payments',
    label: 'Payments',
  },
  {
    id: 'safety',
    label: 'Safety',
  },
  {
    id: 'liability',
    label: 'Liability',
  },
  {
    id: 'privacy',
    label: 'Privacy',
  },
  {
    id: 'governing-law',
    label: 'Governing Law',
  },
];

export const TERMS_INTRO = {
  paragraphs: [
    'Thank you for choosing PeakUp Sports. These Terms of Service and Use (the "Terms") govern access to and use of the PeakUp Sports website, application, software, booking tools, messaging tools, and related marketplace technology (collectively, the "Platform").',
    'The Platform is designed to connect independent service providers, including but not limited to coaches, instructors, guides, mentors, schools, academies, and other sports professionals ("Service Providers"), with users and customers seeking to discover, compare, book, and pay for sports-related services ("Provider Services").',
    'PeakUp Sports is a marketplace and technology provider. Except where expressly stated otherwise in these Terms, PeakUp Sports does not itself provide the Provider Services advertised by Service Providers and is not a party to the underlying service relationship between the Customer and the Service Provider.',
    'Please read these Terms carefully. They contain important information regarding eligibility, booking and payment mechanics, disclaimers, liability limitations, cancellation rules, account suspension rights, and dispute handling.',
    'These Terms incorporate by reference the PeakUp Sports Privacy Policy and any booking, cancellation, payment, or subscription terms expressly referenced on the Platform from time to time.',
  ],
  warnings: [
    'BY ACCESSING, BROWSING, REGISTERING FOR, OR USING THE PLATFORM, OR BY POSTING CONTENT, CREATING A PROFILE, MAKING OR ACCEPTING A BOOKING, OR DOWNLOADING ANY APPLICATION OR CONTENT MADE AVAILABLE BY PEAKUP SPORTS, YOU CONFIRM THAT YOU HAVE READ, UNDERSTAND, AND AGREE TO BE BOUND BY THESE TERMS.',
    'IF YOU DO NOT AGREE TO THESE TERMS, OR IF YOU ARE NOT LEGALLY CAPABLE OF ENTERING INTO A BINDING AGREEMENT, YOU MUST NOT USE THE PLATFORM.',
  ],
};

export const TERMS_GROUPS = [
  {
    navId: 'definitions',
    sections: [
      {
        id: 'section-1',
        number: '01',
        title: 'Definitions',
        definitions: [
          {
            term: 'Account',
            definition: 'means the registered user account created to access or use the Platform.',
          },
          {
            term: 'Booking Summary',
            definition:
              'means the booking confirmation generated by the Platform showing the booked Provider Services, dates, times, location, applicable fees, cancellation terms, and any additional products or services selected at checkout.',
          },
          {
            term: 'Customer',
            definition:
              'means any person who registers for an Account and books Provider Services through the Platform.',
          },
          {
            term: 'Member',
            definition: 'means any registered Customer or registered Service Provider.',
          },
          {
            term: 'Member Content',
            definition:
              'means all text, images, descriptions, profile data, credentials, calendar data, reviews, messages, documents, videos, ratings, and other content that a Member posts, uploads, publishes, transmits, or otherwise makes available through the Platform.',
          },
          {
            term: 'PeakUp Sports',
            definition:
              'means PeakUp Sports, operated by a private individual acting as an independent operator and not yet incorporated as a legal entity.',
          },
          {
            term: 'Platform Fee',
            definition:
              'means the fee or commission charged by PeakUp Sports in connection with the use of the Platform, which may be charged to Customers, Service Providers, or both, depending on the applicable pricing model.',
          },
          {
            term: 'Provider Services',
            definition:
              'means the coaching, instruction, guiding, training, lessons, camps, clinics, tours, programs, rentals, packages, or other sports-related services offered by Service Providers through the Platform, as updated from time to time.',
          },
          {
            term: 'Provider Services Fees',
            definition:
              'means the amounts set by the relevant Service Provider and payable by the Customer in exchange for Provider Services, excluding any separate Platform Fees, taxes, and optional third-party products unless stated otherwise.',
          },
          {
            term: 'Service Provider',
            definition:
              'means any independent coach, instructor, guide, school, academy, or other sports professional or service business that registers on the Platform in order to advertise, offer, and deliver Provider Services.',
          },
          {
            term: 'Service Provider Profile',
            definition:
              'means the public-facing profile created by or for a Service Provider, including qualifications, sport specialities, pricing, availability, locations, languages, reviews, photographs, and service descriptions.',
          },
          {
            term: 'Site',
            definition:
              'means the PeakUp Sports website, any localized domains, landing pages, and any mobile or desktop application through which PeakUp Sports makes the Platform available.',
          },
          {
            term: 'Third-Party Services',
            definition:
              'means products or services supplied by parties other than PeakUp Sports or the relevant Service Provider, including but not limited to payment processing, travel, accommodation, rentals, lift passes, insurance, transport, media, event access, or venue services.',
          },
          {
            term: 'Taxes',
            definition:
              'means all applicable VAT, GST, sales taxes, withholding taxes, tourist taxes, local levies, and similar governmental charges.',
          },
        ],
      },
    ],
  },
  {
    navId: 'platform',
    sections: [
      {
        id: 'section-2',
        number: '02',
        title: 'Modification of the Platform and of These Terms',
        paragraphs: [
          'PeakUp Sports may modify, update, suspend, remove, or replace any part of the Site, Platform, software features, service flows, fees, pricing logic, or these Terms at any time.',
          'If we materially change these Terms, we may provide notice by posting an updated version on the Platform, by email, by in-account notice, or by any other reasonable means. The "Last updated" date at the top of these Terms will also be revised.',
          'Your continued access to or use of the Platform after the effective date of any revised Terms constitutes acceptance of the revised Terms. If you do not agree to the revised Terms, your sole remedy is to stop using the Platform and, where applicable, close your Account.',
        ],
      },
      {
        id: 'section-3',
        number: '03',
        title: 'Nature of the Platform and How It Works',
        paragraphs: [
          'PeakUp Sports operates an online marketplace and booking technology service that allows Customers and Service Providers to find each other, communicate, arrange bookings, process payments, and manage certain related administrative functions.',
        ],
        subsections: [
          {
            label: '3.1 Unregistered visitors.',
            paragraphs: [
              'Visitors who are not registered Members may browse public pages and Service Provider Profiles, subject to these Terms, but must create an Account before making a booking or listing Provider Services.',
            ],
          },
          {
            label: '3.2 Service Providers.',
            paragraphs: [
              'A Service Provider may only offer Provider Services through the Platform after completing the applicable registration and profile setup process and after accepting these Terms and any supplementary onboarding terms required by PeakUp Sports.',
            ],
          },
          {
            label: '3.3 Customers.',
            paragraphs: [
              'A Customer may only book Provider Services through the Platform after creating an Account, providing requested booking information, and completing checkout in accordance with these Terms.',
            ],
          },
          {
            label: '3.4 Marketplace status.',
            paragraphs: [
              'PeakUp Sports is not an employer, principal, partner, joint venturer, franchise operator, or organizer of the Service Providers, and does not supervise or control how Provider Services are delivered. Each Service Provider acts as an independent business or independent professional.',
            ],
          },
          {
            label: '3.5 No party to service contract.',
            paragraphs: [
              'Except for limited payment-collection functions expressly described in these Terms, PeakUp Sports is not a party to the contract formed between the Customer and the Service Provider for the delivery of Provider Services.',
            ],
          },
          {
            label: '3.6',
            paragraphs: [
              'PeakUp Sports is operated globally and does not limit its services to any specific country. Users and Service Providers are responsible for complying with local laws and regulations applicable in their jurisdiction.',
            ],
          },
        ],
      },
      {
        id: 'section-7',
        number: '07',
        title: 'PeakUp Sports Disclaimers Regarding Members, Profiles, and Content',
        paragraphs: [
          "PeakUp Sports does not make any representation, warranty, or guarantee regarding any Member's identity, honesty, quality, conduct, safety, legal compliance, qualifications, insurance status, or suitability.",
        ],
        subsections: [
          {
            label: '7.1 Verification language.',
            paragraphs: [
              'Any reference on the Platform to a Member being "verified", "checked", "confirmed", or similar language only means that a certain registration or review step has been completed; it does not constitute an endorsement, guarantee, or certification by PeakUp Sports.',
            ],
          },
          {
            label: '7.2 No endorsement.',
            paragraphs: [
              'PeakUp Sports does not recommend, endorse, supervise, control, or guarantee any Service Provider, Provider Service, Member Content, review, rating, or statement made by any Member or third party.',
            ],
          },
          {
            label: '7.3 Use at own risk.',
            paragraphs: [
              'Any decision to contact, book, meet, hire, train with, travel with, or otherwise interact with a Service Provider or Customer is made entirely at your own risk.',
            ],
          },
        ],
      },
      {
        id: 'section-15',
        number: '15',
        title: 'Monitoring, Take-Down, and Suspension Rights',
        paragraphs: [
          'PeakUp Sports may, but is not obliged to, monitor, review, screen, audit, moderate, track, or investigate Accounts, profiles, messages, content, bookings, payment flows, or user conduct for legal, safety, fraud-prevention, quality-control, support, or operational purposes.',
        ],
        subsections: [
          {
            label: '15.1 Content removal.',
            paragraphs: [
              'PeakUp Sports may remove or disable access to any Profile, listing, review, message, image, or other content at any time where it believes in good faith that such material breaches these Terms, is unlawful, creates risk, or may harm PeakUp Sports, Members, users, or third parties.',
            ],
          },
          {
            label: '15.2 Suspension and termination.',
            paragraphs: [
              'PeakUp Sports may, in its sole discretion and without liability, suspend, restrict, deactivate, or terminate any Account, profile, listing, payout, booking, or Platform access with or without notice where it suspects breach, fraud, safety issues, chargeback risk, regulatory concern, repeated complaints, content abuse, attempted fee circumvention, or any other conduct inconsistent with the integrity of the Platform.',
            ],
          },
          {
            label: '15.3 Consequences.',
            paragraphs: [
              'If an Account is suspended or terminated, PeakUp Sports may cancel future bookings, notify affected Members, issue refunds, withhold payouts pending investigation, remove content, and refuse future access to the Platform.',
            ],
          },
        ],
      },
    ],
  },
  {
    navId: 'accounts',
    sections: [
      {
        id: 'section-4',
        number: '04',
        title: 'Eligibility and Account Registration',
        paragraphs: [
          'You may use the Platform only if you are legally capable of entering into a binding contract under applicable law and are not prohibited from using the Platform under any applicable law, sanction regime, court order, regulatory restriction, or similar limitation.',
        ],
        subsections: [
          {
            label: '4.1 Minimum age.',
            paragraphs: [
              "The Platform is intended for adults aged 18 or over. Any booking involving a minor participant must be made by that minor's parent or legal guardian, who remains legally responsible for the booking, the participant information provided, and acceptance of all risk and responsibility provisions in these Terms.",
            ],
          },
          {
            label: '4.2 Account accuracy.',
            paragraphs: [
              'You must provide true, current, complete, and accurate information during registration and keep that information updated at all times.',
            ],
          },
          {
            label: '4.3 One account rule.',
            paragraphs: [
              'You may not create more than one active Account for the same role without our written permission. PeakUp Sports may suspend or terminate duplicate, misleading, or fraudulent Accounts.',
            ],
          },
          {
            label: '4.4 Credentials and security.',
            paragraphs: [
              'You are solely responsible for maintaining the confidentiality of your login credentials and for all activity carried out through your Account, whether or not authorized by you. You must notify us immediately if you suspect any unauthorized access or security breach.',
            ],
          },
        ],
      },
      {
        id: 'section-5',
        number: '05',
        title: 'Service Provider Profiles and Service Provider Warranties',
        paragraphs: [
          'A Service Provider must ensure that its Service Provider Profile is accurate, lawful, not misleading, and sufficiently complete for Customers to make informed booking decisions.',
        ],
        subsections: [
          {
            label: '5.1 Required profile information.',
            paragraphs: [
              'PeakUp Sports may require Service Providers to provide, among other things, their legal or trading identity, sports offered, service locations, languages, experience, qualifications, licenses, certifications, insurance details, availability, pricing, cancellation terms, and safety-relevant information.',
            ],
          },
          {
            label: '5.2 Public display.',
            paragraphs: [
              'Service Provider Profiles may be made publicly available on the Site and may be indexed, cached, or previewed by search engines or third-party services. PeakUp Sports is not responsible for third-party caching, indexing, or republication once content is publicly displayed.',
            ],
          },
          {
            label: '5.3 No higher off-platform charge for booked service.',
            paragraphs: [
              'Once a Customer has made a booking through the Platform, the Service Provider may not require that Customer to pay a higher price for the same booked Provider Services than that shown in the Booking Summary, unless the Customer expressly requests additional services or agreed changes through an approved process.',
            ],
          },
          {
            label: '5.4 Service Provider warranties.',
            paragraphs: [
              'By registering and by continuing to use the Platform, each Service Provider represents, warrants, and undertakes that:',
            ],
            items: [
              'it is free to register and contract with PeakUp Sports;',
              'it has and will maintain all qualifications, licenses, permits, registrations, approvals, and insurance required by applicable law and by the nature of the Provider Services offered;',
              'it is competent and legally permitted to deliver the Provider Services it advertises;',
              'its Profile and all Member Content are accurate, current, not misleading, and do not infringe third-party rights;',
              'the Provider Services it offers are legal, safe, and compliant with applicable health, safety, child-protection, consumer, professional, and tax laws;',
              'it will immediately notify PeakUp Sports of any change affecting its eligibility, qualifications, insurance, legal status, or ability to perform booked Provider Services; and',
              'it is solely responsible for the acts, omissions, conduct, equipment, personnel, and subcontracting arrangements connected with its Provider Services.',
            ],
          },
          {
            label: '5.5 Refund obligation if unable to perform.',
            paragraphs: [
              'If a Service Provider cannot deliver booked Provider Services for any reason, it authorizes PeakUp Sports to process any refund or credit due under the applicable cancellation terms or under any mandatory legal requirement.',
            ],
          },
        ],
      },
      {
        id: 'section-6',
        number: '06',
        title: 'Customer Warranties and Customer Responsibilities',
        paragraphs: [
          'By registering and booking through the Platform, each Customer represents, warrants, and undertakes that all booking information supplied is accurate and complete and that the Customer is legally entitled to make the booking.',
        ],
        subsections: [
          {
            label: '6.1 Authority for other participants.',
            paragraphs: [
              'Where the Customer books on behalf of another adult participant or any minor, the Customer confirms that it has obtained all required permissions and accepts responsibility for supplying accurate participant details, including age, ability level, health limitations, and any other information reasonably necessary for safe delivery of the Provider Services.',
            ],
          },
          {
            label: '6.2 Fitness and suitability.',
            paragraphs: [
              'The Customer is responsible for ensuring that each participant is physically and medically fit, properly equipped, and suitable for the booked activity, unless the Service Provider has expressly agreed in writing to assess and supply such suitability requirements.',
            ],
          },
          {
            label: '6.3 Compliance with provider instructions.',
            paragraphs: [
              'Customers and participants must comply with all reasonable safety instructions, equipment requirements, meeting-point rules, conduct standards, local regulations, and participation conditions notified by the Service Provider or by relevant venues or authorities.',
            ],
          },
        ],
      },
      {
        id: 'section-14',
        number: '14',
        title: 'Member Conduct and Prohibited Activities',
        paragraphs: [
          'You are solely responsible for compliance with all laws, regulations, permits, codes, and professional obligations applicable to your use of the Platform and to any Provider Services you offer, book, or receive.',
        ],
        subsections: [
          {
            label: '14.1 Prohibited activities.',
            paragraphs: ['You must not, and must not permit any third party to:'],
            items: [
              'violate any applicable law;',
              'infringe third-party rights;',
              'post false, misleading, illegal, discriminatory, abusive, defamatory, or obscene content;',
              'scrape or systematically extract data;',
              'use bots or automated scripts without permission;',
              'circumvent Platform Fees;',
              'redirect users off-platform to avoid commissions;',
              'create fake bookings, fake reviews, or fake profiles;',
              'list services you are not qualified or authorized to provide;',
              'transmit malware;',
              'interfere with Platform security;',
              'reverse engineer the Platform;',
              'harvest personal data;',
              'impersonate any person or entity; or',
              'use the Platform in a way that harms PeakUp Sports, its Members, or the public.',
            ],
          },
          {
            label: '14.2 Off-platform circumvention.',
            paragraphs: [
              'Any attempt to use the Platform to find Customers or Service Providers and then complete transactions outside the Platform in order to avoid fees is a material breach of these Terms.',
            ],
          },
          {
            label: '14.3 Enforcement rights.',
            paragraphs: [
              'PeakUp Sports may investigate suspected breaches, remove content, freeze payouts, reverse benefits, cancel bookings, notify counterparties, cooperate with authorities, and suspend or terminate Accounts.',
            ],
          },
        ],
      },
    ],
  },
  {
    navId: 'payments',
    sections: [
      {
        id: 'section-8',
        number: '08',
        title: 'Booking Process and Payment Mechanics',
        subsections: [
          {
            label: '8.1 Formation of booking.',
            paragraphs: [
              'When a Customer selects a Service Provider, chooses dates and services, completes checkout, and receives a booking confirmation, a booking arrangement is formed directly between the Customer and the Service Provider on the terms shown in the Booking Summary and any clearly disclosed provider-specific terms that do not conflict with these Terms.',
            ],
          },
          {
            label: '8.2 Payment collection role.',
            paragraphs: [
              'Each Service Provider appoints PeakUp Sports as its limited payment collection agent solely for the purpose of accepting payments from Customers for confirmed bookings and remitting the applicable net amount to the Service Provider, less Platform Fees, payment processing charges, refunds, chargebacks, offsets, taxes, and any other permitted deductions.',
            ],
          },
          {
            label: '8.3 Customer payment authorization.',
            paragraphs: [
              'By completing checkout, the Customer authorizes PeakUp Sports and/or its third-party payment processors to charge the selected payment method for all amounts due, including Provider Services Fees, Platform Fees, applicable taxes, optional extras, and any authorized adjustments or corrections.',
            ],
          },
          {
            label: '8.4 No guarantee of payment timing.',
            paragraphs: [
              'PeakUp Sports will use commercially reasonable efforts to remit amounts due to Service Providers after successful completion of Provider Services, but payout timing may depend on banking systems, verification steps, fraud reviews, reserve holds, chargeback risks, processor rules, tax checks, or other matters outside our control.',
            ],
          },
          {
            label: '8.5 Payment errors.',
            paragraphs: [
              'If a payment processing error occurs, you authorize PeakUp Sports to correct the error by charging, re-charging, crediting, withholding, netting, or reversing the relevant amount using the original payment method or another lawful method.',
            ],
          },
          {
            label: '8.6 Taxes.',
            paragraphs: [
              'Each Service Provider is solely responsible for determining, collecting, reporting, and remitting all taxes applicable to its business and Provider Services, except to the extent PeakUp Sports is expressly required by law to collect or withhold certain taxes.',
            ],
          },
          {
            label: '8.7 Foreign exchange and bank fees.',
            paragraphs: [
              'Banks, card issuers, and payment processors may apply exchange rates, conversion spreads, transfer fees, intermediary bank deductions, or similar charges. PeakUp Sports does not control and is not liable for such charges.',
            ],
          },
        ],
      },
      {
        id: 'section-9',
        number: '09',
        title: 'Platform Fees, Subscriptions, and Other Charges',
        paragraphs: [
          'PeakUp Sports may charge Platform Fees, subscriptions, lead-generation fees, booking commissions, software fees, promotional fees, or other commercial charges to Customers, Service Providers, or both. These may vary by market, sport, country, subscription plan, campaign, or commercial model.',
        ],
        subsections: [
          {
            label: '9.1 Fee disclosure.',
            paragraphs: [
              'Where reasonably practicable, applicable fees are shown before checkout, on invoices, in dashboards, in onboarding materials, or in other commercial documentation made available through the Platform.',
            ],
          },
          {
            label: '9.2 Changes to fees.',
            paragraphs: [
              'PeakUp Sports may amend its pricing structure, Platform Fees, subscription models, and payout deductions at any time in accordance with section 2.',
            ],
          },
          {
            label: '9.3 No refund of non-refundable fees.',
            paragraphs: [
              'Except where required by law or expressly stated otherwise, setup fees, subscription fees, paid promotional products, or similar commercial charges are non-refundable once incurred or activated.',
            ],
          },
        ],
      },
      {
        id: 'section-10',
        number: '10',
        title: 'Cancellations, Changes, Refunds, and No-Shows',
        subsections: [
          {
            label: '10.1 Provider-selected cancellation terms.',
            paragraphs: [
              'PeakUp Sports may permit Service Providers to choose among one or more cancellation policies. The applicable policy will be shown on the Service Provider Profile and/or in the Booking Summary. By making or accepting a booking, both Customer and Service Provider agree that the applicable cancellation policy will govern that booking unless mandatory law requires otherwise.',
            ],
          },
          {
            label: '10.2 Customer cancellations.',
            paragraphs: [
              'If a Customer cancels a booking, any refund will be determined by the applicable cancellation policy, any optional cancellation protection purchased, the timing of cancellation, any non-refundable third-party costs already incurred, and any mandatory legal rights that cannot be excluded.',
            ],
          },
          {
            label: '10.3 Service Provider cancellations.',
            paragraphs: [
              'If a Service Provider cancels a confirmed booking, PeakUp Sports may, at its discretion:',
            ],
            items: [
              'refund the Customer in whole or in part;',
              'help the Customer find an alternative Service Provider;',
              'impose penalties, profile consequences, temporary blocks, fees, or ranking impacts on the cancelling Service Provider; and/or',
              'withhold or offset future payouts to cover refunds, costs, or goodwill gestures.',
            ],
          },
          {
            label: '10.4 Booking changes.',
            paragraphs: [
              'Changes to dates, times, locations, participant counts, or service scope may require mutual agreement and may be subject to new pricing, availability, or cancellation consequences.',
            ],
          },
          {
            label: '10.5 Weather, conditions, closures, and force majeure.',
            paragraphs: [
              "Outdoor and sport activities may be affected by weather, terrain, lift operations, venue access, local restrictions, or safety conditions. Unless PeakUp Sports expressly offers a separate written guarantee, such circumstances do not make PeakUp Sports liable for losses, expenses, or substitute arrangements. Any cancellation or refund outcome will depend on the applicable policy, the Service Provider's assessment, mandatory law, and the specific facts.",
            ],
          },
          {
            label: '10.6 No-shows and lateness.',
            paragraphs: [
              'If a Customer or participant fails to attend, arrives late, lacks required equipment, refuses safety instructions, appears impaired, or cannot participate safely, the Service Provider may treat the booking as a no-show or cancelled session, and a refund may be denied unless mandatory law requires otherwise.',
            ],
          },
          {
            label: '10.7 Chargebacks and payment disputes.',
            paragraphs: [
              'If a Customer initiates a chargeback, card dispute, or payment reversal in respect of a booking, PeakUp Sports may recover the disputed amount, plus related fees and costs, from the relevant Member, may suspend Accounts pending investigation, and may provide booking records, messages, and other evidence to the payment processor or bank.',
            ],
          },
        ],
      },
    ],
  },
  {
    navId: 'safety',
    sections: [
      {
        id: 'section-11',
        number: '11',
        title: 'Risk Assumption; Sports Safety; Minors',
        subsections: [
          {
            label: '11.1 Inherent risks.',
            paragraphs: [
              'Sports, adventure, training, coaching, guiding, outdoor, and physical activities involve inherent and unavoidable risks, including the risk of property damage, equipment failure, weather exposure, falls, collisions, negligence of others, remote locations, inadequate fitness, and serious injury, disability, or death.',
            ],
          },
          {
            label: '11.2 No platform supervision.',
            paragraphs: [
              'PeakUp Sports does not supervise the actual delivery of Provider Services and does not inspect every venue, route, facility, coach, guide, or item of equipment used in connection with Provider Services.',
            ],
          },
          {
            label: '11.3 Customer assumption of risk.',
            paragraphs: [
              'To the fullest extent permitted by law, each Customer and participant knowingly and voluntarily assumes all risks arising out of or related to any Provider Services booked through the Platform, whether occurring before, during, or after the activity, and whether caused by natural conditions, third parties, other participants, or the Service Provider.',
            ],
          },
          {
            label: '11.4 Minors.',
            paragraphs: [
              "Any booking involving a minor must be made by a parent or legal guardian. The parent or legal guardian confirms that it has authority to bind itself and, to the extent permitted by law, the minor participant, and accepts responsibility for the minor's participation, conduct, equipment, transport arrangements, medical suitability, emergency decision-making arrangements, and compliance with provider instructions.",
            ],
          },
          {
            label: '11.5 Additional waivers.',
            paragraphs: [
              'PeakUp Sports or the relevant Service Provider may require a separate risk waiver, health declaration, parental consent form, or event-specific release before participation. Failure to complete required documents may result in refusal of participation without refund where permitted by law.',
            ],
          },
        ],
      },
      {
        id: 'section-19',
        number: '19',
        title: 'Complaints, Safety Reports, and Misconduct',
        subsections: [
          {
            label: '19.1 Customer complaints.',
            paragraphs: [
              'If a Customer believes that booked Provider Services were materially misdescribed or not delivered as booked, the Customer should notify PeakUp Sports promptly through the Platform or via the support contact listed below. PeakUp Sports may, but is not obliged to, review the complaint and facilitate communication.',
            ],
          },
          {
            label: '19.2 Misconduct and emergencies.',
            paragraphs: [
              'If you believe that a person has acted dangerously, violently, abusively, sexually inappropriately, fraudulently, or otherwise unlawfully, you should first contact the appropriate emergency services, police, rescue service, medical provider, or local authority. You should then report the matter to PeakUp Sports with any relevant incident information.',
            ],
          },
          {
            label: '19.3 No duty to mediate.',
            paragraphs: [
              'PeakUp Sports may, at its discretion, assist with dispute resolution or safety follow-up, but has no obligation to mediate or resolve disputes between Members.',
            ],
          },
        ],
      },
    ],
  },
  {
    navId: 'liability',
    sections: [
      {
        id: 'section-12',
        number: '12',
        title: 'Warranty Disclaimer',
        warnings: [
          'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SITE, PLATFORM, CONTENT, MEMBER CONTENT, COLLECTIVE CONTENT, PAYMENT FLOWS, COMMUNICATION TOOLS, AND ALL RELATED SERVICES ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITH ALL FAULTS AND WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE.',
          'WITHOUT LIMITING THE FOREGOING, PEAKUP SPORTS DISCLAIMS ALL WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, SATISFACTORY QUALITY, TITLE, NON-INFRINGEMENT, ACCURACY, UPTIME, AVAILABILITY, SECURITY, QUIET ENJOYMENT, AND ANY WARRANTIES ARISING OUT OF COURSE OF DEALING, COURSE OF PERFORMANCE, OR USAGE OF TRADE.',
          'PEAKUP SPORTS DOES NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, COMPLETELY SECURE, FREE FROM MALWARE, OR COMPATIBLE WITH YOUR DEVICE OR PAYMENT METHOD, NOR THAT ANY MEMBER, PROFILE, REVIEW, MESSAGE, BOOKING, PROVIDER SERVICE, THIRD-PARTY SERVICE, OR RESULT WILL MEET YOUR EXPECTATIONS OR REQUIREMENTS.',
        ],
      },
      {
        id: 'section-13',
        number: '13',
        title: 'Disclaimer of Liability and Liability Cap',
        subsections: [
          {
            label: '13.1 Excluded losses.',
            paragraphs: [
              'To the fullest extent permitted by law, PeakUp Sports shall not be liable for any indirect, incidental, special, consequential, exemplary, or punitive damages, or for any loss of profits, revenue, data, goodwill, reputation, opportunity, business interruption, substitute-service costs, travel costs, accommodation costs, or emotional distress, arising out of or related to the Platform, the Provider Services, or these Terms.',
            ],
          },
          {
            label: '13.2 Third-party and member conduct.',
            paragraphs: [
              'PeakUp Sports is not liable for the acts, omissions, negligence, misconduct, statements, reviews, content, quality, legality, safety, or failure to perform of any Service Provider, Customer, participant, venue, processor, or third party.',
            ],
          },
          {
            label: '13.3 Bodily injury and sports losses.',
            paragraphs: [
              'To the fullest extent permitted by law, PeakUp Sports is not liable for personal injury, illness, death, property damage, theft, loss of equipment, transportation issues, weather-related losses, or any consequences arising from participation in Provider Services booked through the Platform.',
            ],
          },
          {
            label: '13.4 Maximum aggregate liability.',
            paragraphs: [
              'If, notwithstanding the exclusions above, PeakUp Sports is found liable to a Member for any claim arising out of or relating to these Terms or the Platform, the maximum aggregate liability of PeakUp Sports shall not exceed: (a) for a Customer, the total Platform Fees and Provider Services Fees actually paid by that Customer through the Platform in the twelve (12) months preceding the event giving rise to the claim; and (b) for a Service Provider, the total amount actually remitted by PeakUp Sports to that Service Provider in the twelve (12) months preceding the event giving rise to the claim. If mandatory law does not permit that cap, liability shall be limited to the minimum extent permitted by law.',
            ],
          },
          {
            label: '13.5 Essential basis of bargain.',
            paragraphs: [
              'The disclaimers, exclusions, and liability limitations in these Terms form an essential basis of the agreement between you and PeakUp Sports and apply whether the claim is based in contract, tort, negligence, statutory duty, misrepresentation, restitution, or any other legal theory.',
            ],
          },
        ],
      },
      {
        id: 'section-18',
        number: '18',
        title: 'Indemnity',
        paragraphs: [
          'To the fullest extent permitted by law, you agree to defend, indemnify, and hold harmless PeakUp Sports, its affiliates, officers, directors, employees, contractors, agents, successors, and assigns from and against any and all claims, demands, investigations, proceedings, liabilities, damages, judgments, settlements, penalties, fines, losses, costs, and expenses, including reasonable legal and professional fees, arising out of or related to: (a) your use of the Platform; (b) your breach of these Terms; (c) your Member Content; (d) your Provider Services or participation in Provider Services; (e) your breach of applicable law; (f) your interaction with any Member or third party; or (g) any injury, loss, damage, or dispute caused by your acts or omissions.',
          'PeakUp Sports reserves the right to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, in which case you will cooperate fully at your own expense.',
        ],
      },
    ],
  },
  {
    navId: 'privacy',
    sections: [
      {
        id: 'section-16',
        number: '16',
        title: 'Privacy and Data Protection',
        paragraphs: [
          'Your use of the Platform is subject to the PeakUp Sports Privacy Policy, as amended from time to time.',
        ],
        subsections: [
          {
            label: '16.1 Data processing.',
            paragraphs: [
              'By using the Platform, you acknowledge that PeakUp Sports may collect, use, store, transfer, and otherwise process personal data for account management, bookings, payments, fraud prevention, support, analytics, legal compliance, marketing where permitted, and Platform improvement.',
            ],
          },
          {
            label: '16.2 Member-to-member data.',
            paragraphs: [
              'Where personal data is exchanged between Customers and Service Providers for the purpose of carrying out Provider Services, each Member is independently responsible for complying with applicable privacy and data-protection laws in relation to that data.',
            ],
          },
          {
            label: '16.3 Processors and cross-border transfers.',
            paragraphs: [
              'PeakUp Sports may use third-party processors and may transfer data internationally where permitted by law and subject to appropriate safeguards.',
            ],
          },
        ],
      },
    ],
  },
  {
    navId: 'governing-law',
    sections: [
      {
        id: 'section-17',
        number: '17',
        title: 'Intellectual Property',
        paragraphs: [
          'All rights, title, and interest in and to the Platform, Site, software, design, layout, text, graphics, logos, compilations, databases, and all PeakUp Sports content and marks, excluding Member Content, are and remain the property of PeakUp Sports and/or its licensors.',
        ],
        subsections: [
          {
            label: '17.1 License to PeakUp Sports.',
            paragraphs: [
              'By posting or uploading Member Content, you grant PeakUp Sports a worldwide, non-exclusive, royalty-free, sublicensable license to host, store, reproduce, adapt, display, distribute, and use that Member Content for the operation, promotion, improvement, and protection of the Platform, subject to the Privacy Policy.',
            ],
          },
          {
            label: '17.2 Member responsibility.',
            paragraphs: [
              'You are solely responsible for ensuring that your Member Content does not infringe any third-party intellectual property, privacy, publicity, database, or contractual rights.',
            ],
          },
          {
            label: '17.3 Reservation of rights.',
            paragraphs: [
              'No rights are granted to you other than the limited right to use the Platform in accordance with these Terms.',
            ],
          },
        ],
      },
      {
        id: 'section-20',
        number: '20',
        title: 'Termination by You',
        paragraphs: [
          'You may stop using the Platform at any time and may request account closure in accordance with the account settings or support process then available.',
          'Termination or closure of your Account does not affect rights or obligations accrued before termination, including payment obligations, refunds, chargeback recoveries, indemnities, liability exclusions, intellectual property rights, and any provisions that by their nature are intended to survive.',
        ],
      },
      {
        id: 'section-21',
        number: '21',
        title: 'General Provisions',
        subsections: [
          {
            label: '21.1 Entire agreement.',
            paragraphs: [
              'These Terms constitute the entire agreement between you and PeakUp Sports concerning the Platform and supersede all prior oral and written understandings relating to the same subject matter.',
            ],
          },
          {
            label: '21.2 Force majeure.',
            paragraphs: [
              'PeakUp Sports shall not be liable for delay or failure caused by events beyond its reasonable control, including acts of God, severe weather, pandemic, epidemic, war, terrorism, civil unrest, labor disputes, government action, cyberattack, processor outage, internet failure, utility interruption, transport disruption, venue closure, or supplier failure.',
            ],
          },
          {
            label: '21.3 Assignment.',
            paragraphs: [
              'You may not assign, transfer, or novate your rights or obligations under these Terms without our prior written consent. PeakUp Sports may assign or transfer these Terms or any rights and obligations under them at any time.',
            ],
          },
          {
            label: '21.4 No waiver.',
            paragraphs: [
              'A failure or delay by PeakUp Sports to enforce any provision shall not constitute a waiver of that provision or of any other rights.',
            ],
          },
          {
            label: '21.5 Severability.',
            paragraphs: [
              'If any provision of these Terms is held invalid or unenforceable, the remaining provisions shall remain in full force to the maximum extent permitted by law.',
            ],
          },
          {
            label: '21.6 Language and notices.',
            paragraphs: [
              'PeakUp Sports may give notices by posting on the Platform, by email, or by other reasonable means. The English version of these Terms shall control unless PeakUp Sports expressly states otherwise.',
            ],
          },
          {
            label: '21.7 No third-party rights.',
            paragraphs: [
              'Except where expressly stated, no person other than the parties to these Terms shall have any right to enforce them.',
            ],
          },
        ],
      },
      {
        id: 'section-22',
        number: '22',
        title: 'Governing Law and Jurisdiction',
        paragraphs: [
          'These Terms and any dispute or claim arising out of or in connection with them, their subject matter, or their formation, including non-contractual disputes or claims, shall be governed by the laws of Switzerland, unless mandatory consumer law requires otherwise.',
          'Unless mandatory law requires a different forum, the courts at Switzerland shall have exclusive jurisdiction. PeakUp Sports may also seek injunctive or protective relief in any competent jurisdiction.',
        ],
      },
      {
        id: 'section-23',
        number: '23',
        title: 'Contact Details',
        paragraphs: [
          'For questions about these Terms, legal notices, or support matters, please contact:',
          'hello@peakupsports.com',
        ],
      },
    ],
  },
];
