// NOTE: this server is purely a dev-mode server. In production, the
// server/index.js server also serves the API routes.

// Configure process.env with .env.* files
require('./env').configureEnv();

const express = require('express');
const compression = require('compression');
const cookieParser = require('cookie-parser');
const bodyParser = require('body-parser');
const cors = require('cors');
const apiRouter = require('./apiRouter');
const wellKnownRouter = require('./wellKnownRouter');
const webmanifestResourceRoute = require('./resources/webmanifest');
const robotsTxtRoute = require('./resources/robotsTxt');
const sitemapResourceRoute = require('./resources/sitemap');

const radix = 10;
const PORT = parseInt(process.env.REACT_APP_DEV_API_SERVER_PORT || '3500', radix);
const app = express();

const marketplaceRootUrl =
  process.env.REACT_APP_MARKETPLACE_ROOT_URL || 'http://localhost:3000';
const devCorsOrigins = new Set([
  marketplaceRootUrl,
  'http://localhost:3000',
  'http://127.0.0.1:3000',
]);

const isPrivateLanHostname = hostname =>
  /^192\.168\.\d{1,3}\.\d{1,3}$/.test(hostname) ||
  /^10\.\d{1,3}\.\d{1,3}\.\d{1,3}$/.test(hostname) ||
  /^172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}$/.test(hostname);

const isDevCorsOriginAllowed = origin => {
  if (!origin) {
    return true;
  }
  if (devCorsOrigins.has(origin)) {
    return true;
  }
  try {
    const { hostname, protocol } = new URL(origin);
    if (protocol !== 'http:' && protocol !== 'https:') {
      return false;
    }
    if (hostname === 'localhost' || hostname === '127.0.0.1') {
      return true;
    }
    if (isPrivateLanHostname(hostname)) {
      return true;
    }
    const marketplaceHostname = new URL(marketplaceRootUrl).hostname;
    return hostname === marketplaceHostname;
  } catch (e) {
    return false;
  }
};

// NOTE: CORS is only needed in this dev API server because it's
// running in a different port than the main app.
app.use(
  cors({
    origin(origin, callback) {
      if (isDevCorsOriginAllowed(origin)) {
        callback(null, origin || marketplaceRootUrl);
      } else {
        // eslint-disable-next-line no-console
        console.warn(`[PeakUp API CORS] blocked origin: ${origin}`);
        callback(null, false);
      }
    },
    credentials: true,
  })
);
app.use(cookieParser());
app.use('/.well-known', wellKnownRouter);
app.use('/api', apiRouter);

// Generate web app manifest
// When developing with "yarn run dev",
// you can reach the manifest from http://localhost:3500/site.webmanifest
// The corresponding <link> element is set in src/components/Page/Page.js
app.get('/site.webmanifest', webmanifestResourceRoute);

// robots.txt and sitemap-* fetches should return similarly compressed data as server/index.js
app.use(compression());

// robots.txt is generated by resources/robotsTxt.js
// It creates the sitemap URL with the correct marketplace URL
app.get('/robots.txt', robotsTxtRoute);

// Handle different sitemap-* resources. E.g. /sitemap-index.xml
app.get('/sitemap-:resource', sitemapResourceRoute);

const server = app.listen(PORT, '0.0.0.0', () => {
  // eslint-disable-next-line no-console
  console.log(`API server listening on 0.0.0.0:${PORT}`);
});

server.on('error', err => {
  if (err.code === 'EADDRINUSE') {
    // eslint-disable-next-line no-console
    console.error(
      `[PeakUp API] Port ${PORT} is already in use. Stop other dev API processes (another yarn dev or dev-backend).`
    );
  } else {
    // eslint-disable-next-line no-console
    console.error('[PeakUp API] Server failed to start:', err);
  }
  process.exit(1);
});
